name: guia_click
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

isar_version: &isar_version 3.3.0

dependencies:
  algolia_helper_flutter: ^1.2.0
  algoliasearch: ^1.31.2
  auto_route: ^8.1.0
  bloc: ^9.0.0
  collection: ^1.19.0
  custom_rating_bar: ^3.0.0
  equatable: ^2.0.7
  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.19.0
  otp_pin_field: ^1.4.1
  shared_preferences: ^2.5.3
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  isar_community_generator: *isar_version

  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
