name: guia_click
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

isar_version: &isar_version 3.3.0

dependencies:
  algolia_helper_flutter: ^1.6.0
  algoliasearch: ^1.43.1
  auto_route: ^11.1.0
  bloc: ^9.2.0
  collection: ^1.19.1
  custom_rating_bar: ^3.0.0
  equatable: ^2.0.8
  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  otp_pin_field: ^1.4.1
  shared_preferences: ^2.5.4
  very_good_analysis: ^10.0.0

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.7.1
  isar_community_generator: *isar_version

  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
